In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [14]:
a = np.zeros((2,3))
b = np.ones((3,2),dtype = "int64")
c = np.full((3,3),5.1)
d = np.random.randint(high = 10,size = (2,3),low=5)

In [7]:
print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [8]:
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [11]:
c

array([[5.1, 5.1, 5.1],
       [5.1, 5.1, 5.1],
       [5.1, 5.1, 5.1]])

In [15]:
d

array([[5, 5, 5],
       [8, 5, 7]])

In [17]:
e = np.arange(1,10)
print(e)

[1 2 3 4 5 6 7 8 9]


In [20]:
#axis = 0 means column
#axis = 1 means row
np.sum(d,axis = 1)

array([15, 20])

In [33]:
d[:,0:2]

array([[5, 5],
       [8, 5]])

In [29]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
a+b

array([6, 6, 6, 6, 6])

In [31]:
a**2

array([ 1,  4,  9, 16, 25])