In [1]:
import pandas as pd
import numpy as np

In [2]:
marks = {
    "MarksA":np.random.randint(1,100,5),
    "MarksB":np.random.randint(50,100,5),
    "MarksC":np.random.randint(30,100,5)
}
marks

{'MarksA': array([95, 22, 80, 73, 84]),
 'MarksB': array([61, 64, 83, 76, 93]),
 'MarksC': array([97, 99, 43, 31, 92])}

In [3]:
df = pd.DataFrame(marks)
print(df)

   MarksA  MarksB  MarksC
0      95      61      97
1      22      64      99
2      80      83      43
3      73      76      31
4      84      93      92


In [5]:
df.head(n=3)#by Default n = 5

MarksA  MarksB  MarksC
0      95      61      97
1      22      64      99
2      80      83      43

In [6]:
print(df.columns)

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')


In [7]:
df.to_csv("Marks.csv")#index = True for storing indexies

In [9]:
myData = pd.read_csv("Marks.csv")
myData = myData.drop(columns=["Unnamed: 0"])
myData

MarksA  MarksB  MarksC
0      95      61      97
1      22      64      99
2      80      83      43
3      73      76      31
4      84      93      92

In [10]:
a = df.to_numpy()
# a = df.values   #Depricated
print(a,type(a))

[[95 61 97]
 [22 64 99]
 [80 83 43]
 [73 76 31]
 [84 93 92]] <class 'numpy.ndarray'>


In [11]:
df["MarksA"]

0    95
1    22
2    80
3    73
4    84
Name: MarksA, dtype: int64